# Generated by Django 4.1.4 on 2023-01-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='bitrate_audio',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='bitrate_video',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='size',
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_pid',
            field=models.CharField(default='0000', max_length=100, verbose_name='PID'),
        ),
    ]
