version: "3.3"

services:

  web:
    container_name: Web
    build: .
    command: bash -c "python3 manage.py runserver 0.0.0.0:22222"
    restart: always
    volumes:
      - .:/app
    ports:
      - "22222:22222"
    networks:
      - web
      
networks:
  web:
    driver: bridge