# Generated by Django 4.1.4 on 2022-12-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('preview', models.ImageField(upload_to='image')),
                ('first_team_flag', models.ImageField(upload_to='image')),
                ('second_team_flag', models.ImageField(upload_to='image')),
                ('date', models.DateField()),
                ('is_pay', models.CharField(choices=[('PAY', 'Платно'), ('NOT_PAY', 'Бесплатно')], max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.category')),
            ],
        ),
    ]
