# Generated by Django 4.1.4 on 2022-12-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_alter_translation_first_team_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='preview',
            field=models.ImageField(height_field=225, upload_to='images', width_field=339),
        ),
    ]
