# Generated by Django 4.1.4 on 2022-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_translation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sup_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='date',
            field=models.DateField(verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='description',
            field=models.TextField(default='Прямая трансляция', max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='first_team',
            field=models.CharField(default='Команда 1', max_length=30, verbose_name='Название первой команды'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='first_team_flag',
            field=models.ImageField(upload_to='images', verbose_name='Флаг первой команды'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='is_pay',
            field=models.CharField(choices=[('Платно', 'Платно'), ('Бесплатно', 'Бесплатно')], max_length=50, verbose_name='Доступ к трансляции'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка на поток'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название трансляции'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='preview',
            field=models.ImageField(upload_to='images', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='second_team',
            field=models.CharField(default='Команда 2', max_length=30, verbose_name='Название второй команды'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='second_team_flag',
            field=models.ImageField(upload_to='images', verbose_name='Флаг второй команды'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='time',
            field=models.TimeField(verbose_name='Время события'),
        ),
    ]
