# Generated by Django 4.1.4 on 2023-01-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0029_alter_usersubs_end_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.category'),
        ),
    ]
