# Generated by Django 4.1.4 on 2023-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0030_subscription_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sup_price',
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_price_year',
            field=models.CharField(max_length=100, null=True, verbose_name='Цена за год'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_price_year_discount',
            field=models.CharField(max_length=100, null=True, verbose_name='Скидка при покупке годовой подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_price_year_month',
            field=models.CharField(max_length=100, null=True, verbose_name='Цена за месяц при годовой подписке'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sup_price_month',
            field=models.CharField(max_length=100, null=True, verbose_name='Цена за месяц'),
        ),
    ]
