# Generated by Django 4.1.4 on 2023-01-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0031_remove_subscription_sup_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='online',
            field=models.IntegerField(null=True, verbose_name='Смотрят сейчас'),
        ),
    ]
