# Generated by Django 4.1.4 on 2022-12-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='description',
            field=models.TextField(default='Матч', max_length=500),
        ),
    ]
