# Generated by Django 4.1.4 on 2022-12-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_translation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='description',
        ),
    ]
