# Generated by Django 4.1.4 on 2022-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_translation_first_team_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='first_team_flag',
            field=models.ImageField(upload_to='mainsite/static/image'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='preview',
            field=models.ImageField(upload_to='mainsite/static/image'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='second_team_flag',
            field=models.ImageField(upload_to='mainsite/static/image'),
        ),
    ]
