# Generated by Django 4.1.4 on 2022-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_alter_translation_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='time',
            field=models.TimeField(default='12'),
        ),
    ]
