# Generated by Django 4.1.4 on 2022-12-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_translation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='time',
            field=models.TimeField(),
        ),
    ]
