# Generated by Django 4.1.4 on 2022-12-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_author',
            field=models.TextField(default='Неизвестен', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=30000),
        ),
    ]
