# Generated by Django 4.1.4 on 2022-12-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_subscription_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='LIVE'),
        ),
    ]
