# Generated by Django 4.1.4 on 2023-01-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_news_dislikes_news_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_author',
            field=models.TextField(default='Неизвестен', max_length=100, verbose_name='Автор фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to='images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=30000, verbose_name='Текс'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_name',
            field=models.CharField(max_length=100, verbose_name='Название подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sup_price',
            field=models.CharField(max_length=100, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст Коментария')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.news')),
            ],
        ),
    ]
