# Generated by Django 4.1.4 on 2023-01-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0026_usersubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.subscription'),
        ),
    ]
