# Generated by Django 4.1.4 on 2023-01-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0027_translation_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newscomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии к новостям'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'Трансляция', 'verbose_name_plural': 'Трансляции'},
        ),
        migrations.AlterModelOptions(
            name='translationcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии к трансляциям'},
        ),
        migrations.AlterModelOptions(
            name='usersubs',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='usersubs',
            name='end_sub',
            field=models.DateTimeField(null=True, verbose_name='Конец действия подписки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=30000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='translationcomment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст коментария'),
        ),
    ]
