# Generated by Django 4.1.4 on 2023-01-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0032_translation_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='online',
            field=models.IntegerField(default=0, verbose_name='Смотрят сейчас'),
        ),
    ]
