# Generated by Django 4.1.4 on 2023-01-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('input_stream', models.CharField(max_length=500, verbose_name='Входной поток')),
                ('output_stream', models.CharField(max_length=500, verbose_name='Выходной поток')),
                ('bitrate_video', models.CharField(max_length=100, verbose_name='Битрейт видео')),
                ('bitrate_audio', models.CharField(max_length=100, verbose_name='Битрейт аудио')),
                ('size', models.CharField(max_length=100, verbose_name='Разрешение (1920x1080)')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
    ]
